# 像素风皮肤生成器：字符画 -> SVG（水平同色段合并为 rect，A/B 双帧 steps 切换）
# 参考路线：Clawd / Shimeji / DyberPet 等开源桌宠的像素 sprite 传统。
# 用法：powershell -File make-pixel-skins.ps1
$ErrorActionPreference = 'Stop'

$W = 28
$H = 32
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

# ---- 调色板（限色，像素艺术惯例） ----
$palNailong = @{
  o = '#4a3218'  # 轮廓深棕
  y = '#ffd54f'  # 主黄
  l = '#ffe58a'  # 受光亮黄
  d = '#ecb23c'  # 暗黄体积
  c = '#fff3c2'  # 肚皮奶油
  w = '#fffbe8'  # 角/翅膀白
  k = '#33251a'  # 眼黑
  h = '#ffffff'  # 高光
  r = '#ff9d8a'  # 腮红
  p = '#ff9fb0'  # 口内/尾心粉
  m = '#c98f3d'  # 鼻孔
  x = '#ffb03a'  # 感叹号
}
$palSnow = @{
  o = '#3d4a5c'  # 轮廓蓝灰
  w = '#f6f9fd'  # 白主体
  b = '#d7e3ef'  # 阴影蓝
  i = '#ffffff'  # 顶部受光
  p = '#ffc9d4'  # 耳内粉/腮红
  e = '#7ec8e3'  # 围巾冰蓝
  f = '#5aa8c9'  # 围巾暗/音符/思考点
  k = '#2e3b4a'  # 眼黑
  n = '#3a4a5a'  # 鼻
  x = '#ffb03a'  # 感叹号
}

function Rows($s) {
  @($s -split "`r?`n" | Where-Object { $_ -ne '' })
}

function ConvertTo-Rects([string[]]$rows, [hashtable]$pal, [string]$what, [bool]$full) {
  if ($full -and $rows.Count -ne $H) { throw "$what 行数 $($rows.Count) != $H" }
  if ($rows.Count -gt $H) { throw "$what 行数 $($rows.Count) 超出 $H" }
  $out = New-Object System.Text.StringBuilder
  $w0 = $rows[0].Length
  for ($yy = 0; $yy -lt $rows.Count; $yy++) {
    $r = $rows[$yy]
    if ($full -and $r.Length -ne $W) { throw "$what 第 $yy 行长度 $($r.Length) != $W : $r" }
    if (-not $full -and $r.Length -ne $w0) { throw "$what 第 $yy 行长度 $($r.Length) != $w0 : $r" }
    $x = 0
    while ($x -lt $r.Length) {
      $ch = [string]$r[$x]
      if ($ch -eq '.') { $x++; continue }
      if (-not $pal.ContainsKey($ch)) { throw "$what 未知字符 '$ch' @ ($x,$yy)" }
      $run = 1
      while ($x + $run -lt $r.Length -and [string]$r[$x + $run] -eq $ch) { $run++ }
      [void]$out.Append("<rect x=`"$x`" y=`"$yy`" width=`"$run`" height=`"1`" fill=`"$($pal[$ch])`"/>")
      $x += $run
    }
  }
  $out.ToString()
}

$cssTemplate = @'
.fa{opacity:1}.fb{opacity:0}
.fa,.fb{animation-iteration-count:infinite;animation-timing-function:steps(1,end);animation-duration:__DUR__s}
.fa{animation-name:fa}.fb{animation-name:fb}
@keyframes fa{0%,49.99%{opacity:1}50%,100%{opacity:0}}
@keyframes fb{0%,49.99%{opacity:0}50%,100%{opacity:1}}
.ov{opacity:0}
.blink{animation:blink 4.4s infinite}
@keyframes blink{0%,93.4%,100%{opacity:0}93.5%,99%{opacity:1}}
.td{animation:tdot 1.5s steps(1) infinite}
.td2{animation-delay:.5s}.td3{animation-delay:1s}
@keyframes tdot{0%,32%{opacity:1}33%,100%{opacity:0}}
.note{animation:note .72s steps(2) infinite}
@keyframes note{50%{transform:translateY(-3px)}}
.mark{animation:mark 1s steps(1) infinite}
@keyframes mark{0%,49%{opacity:1}50%,100%{opacity:.15}}
.shake{animation:shake .14s steps(2) infinite}
@keyframes shake{50%{transform:translateX(1px)}}
'@

function New-SkinSvg([string]$file, [hashtable]$pal, [string[]]$frameA, [string[]]$frameB, [double]$dur, $overlays, [bool]$shake) {
  $what = [IO.Path]::GetFileName($file)
  $a = ConvertTo-Rects $frameA $pal "$what/A" $true
  $b = ConvertTo-Rects $frameB $pal "$what/B" $true
  $ov = ''
  foreach ($ol in $overlays) {
    $r = ConvertTo-Rects $ol.rows $pal "$what/overlay@($($ol.x),$($ol.y))" $false
    $ov += "<g class=`"ov $($ol.cls)`" transform=`"translate($($ol.x),$($ol.y))`">$r</g>"
  }
  $css = $cssTemplate.Replace('__DUR__', ([string]$dur))
  $inner = "<g class=`"fa`">$a</g><g class=`"fb`">$b</g>"
  if ($shake) { $inner = "<g class=`"shake`">$inner</g>" }
  $svg = "<svg xmlns=`"http://www.w3.org/2000/svg`" viewBox=`"0 0 $W $H`" width=`"$W`" height=`"$H`" shape-rendering=`"crispEdges`">" +
    "<style>$css</style>$inner$ov</svg>"
  [IO.File]::WriteAllText($file, $svg)
  Write-Host "生成 $what ($([math]::Round((Get-Item $file).Length/1KB,1)) KB)"
}

# ---- 覆盖层字符画 ----
$blinkNailong = Rows @'
yyyyyyyyyy
yyyyyyyyyy
oooyyyyooo
yyyyyyyyyy
'@

$blinkSnow = Rows @'
wwwwwwwwww
oooowwoooo
'@

$noteNailong = Rows @'
..oo
...o
...o
oooo
oo..
'@

$noteSnow = Rows @'
..ff
...f
...f
ffff
ff..
'@

$markAll = Rows @'
xx
xx
xx
xx
..
xx
'@

$tdotNailong = Rows @'
d
'@
$tdotSnow = Rows @'
f
'@

# ============================================================
# 奶龙（像素小奶龙：弯角 + 小翅膀 + 心形尾尖）
# ============================================================
$nlIdleA = Rows @'
............................
......owo...owwo...owo......
......owwo.owwwwo.owwwo.....
.......owo..wwww..owo.......
........oyyywwwwyyyo........
.......ollllllllllllo.......
......oyyyyyyyyyyyyyyo......
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyyykhkyyyykhkyydo.....
.....oyyykkhyyyykkhyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyrryyyyyyyyyyrrdo.....
.....oyyyyyyymmyyyyyydo.....
.....oyyyyyyoyyoyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.......oyyyyyyyyyyydo.......
.........oyyyyyyyyo.........
........oyyyyyyyyyyo........
........oyyccccccyyo........
....owwooyyccccccyyoowwo....
...owwwooyyccccccyyoowwwo...
...owwwooyyccccccyyoowwwo...
....owwooyyccccccyyoowwo....
.....oo.oyyccccccyyo.oo.....
........oyyddddddyyo..oyo...
.........oyyyyyyyyo....oyo..
........oddooooooddo...oppo.
.........oo......oo.........
............................
'@

$nlIdleB = Rows @'
............................
............................
......owo...owwo...owo......
......owwo.owwwwo.owwwo.....
.......owo..wwww..owo.......
........oyyywwwwyyyo........
.......ollllllllllllo.......
......oyyyyyyyyyyyyyyo......
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyyykhkyyyykhkyydo.....
.....oyyykkhyyyykkhyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyrryyyyyyyyyyrrdo.....
.....oyyyyyyymmyyyyyydo.....
.....oyyyyyyoyyoyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.......oyyyyyyyyyyydo.......
.........oyyyyyyyyo.........
........oyyccccccyyo........
...owwwooyyccccccyyoowwwo...
...owwwooyyccccccyyoowwwo...
....owwooyyccccccyyoowwo....
.....oo.oyyccccccyyo.oo.....
........oyyccccccyyo........
........oyyddddddyyo..oyo...
.........oyyyyyyyyo....oyo..
........oddooooooddo...oppo.
.........oo......oo.........
............................
'@

$nlThinkA = Rows @'
............................
......owo...owwo...owo......
......owwo.owwwwo.owwwo.....
.......owo..wwww..owo.......
........oyyywwwwyyyo........
.......ollllllllllllo.......
......oyyyyyyyyyyyyyyo......
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyrryyyyyyyyyyrrdo.....
.....oyyyyyyymmyyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.......oyyyyyyyyyyydo.......
.........oyyyyyyyyo.........
........oyyyyyyyyyyo........
........oyyccccccyyo........
....owwooyyccccccyyoowwo....
...owwwooyyccccccyyoowwwo...
...owwwooyyccccccyyoowwwo...
....owwooyyccccccyyoowwo....
.....oo.oyyccccccyyo.oo.....
........oyyddddddyyo..oyo...
.........oyyyyyyyyo....oyo..
........oddooooooddo...oppo.
.........oo......oo.........
............................
'@

$nlThinkB = Rows @'
............................
......owo...owwo...owo......
......owwo.owwwwo.owwwo.....
.......owo..wwww..owo.......
........oyyywwwwyyyo........
.......ollllllllllllo.......
......oyyyyyyyyyyyyyyo......
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyrryyyyyyyyyyrrdo.....
.....oyyyyyyymmyyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.......oyyyyyyyyyyydo.......
.........oyyyyyyyyo.........
........oyyyyyyyyyyo........
........oyyccccccyyo........
....owwooyyccccccyyoowwo....
...owwwooyyccccccyyoowwwo...
...owwwooyyccccccyyoowwwo...
....owwooyyccccccyyoowwo....
.....oo.oyyccccccyyo.oo.....
........oyyddddddyyo..oyo...
.........oyyyyyyyyo....oyo..
........oddooooooddo...oppo.
.........oo......oo.........
............................
'@

$nlSpeakA = Rows @'
............................
......owo...owwo...owo......
......owwo.owwwwo.owwwo.....
.......owo..wwww..owo.......
........oyyywwwwyyyo........
.......ollllllllllllo.......
......oyyyyyyyyyyyyyyo......
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyykykyyyykykyydo.....
.....oyyyykyyyyykyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyrryyyyyyyyyyrrdo.....
.....oyyyyyyymmyyyyyydo.....
.....oyyyyyyoppoyyyyydo.....
.....oyyyyyyyppyyyyyydo.....
.......oyyyyyyyyyyydo.......
.........oyyyyyyyyo.........
........oyyyyyyyyyyo........
........oyyccccccyyo........
....owwooyyccccccyyoowwo....
...owwwooyyccccccyyoowwwo...
...owwwooyyccccccyyoowwwo...
....owwooyyccccccyyoowwo....
.....oo.oyyccccccyyo.oo.....
........oyyddddddyyo..oyo...
.........oyyyyyyyyo....oyo..
........oddooooooddo...oppo.
.........oo......oo.........
............................
'@

$nlAlertA = Rows @'
............................
......owo...owwo...owo......
......owwo.owwwwo.owwwo.....
.......owo..wwww..owo.......
........oyyywwwwyyyo........
.......ollllllllllllo.......
......oyyyyyyyyyyyyyyo......
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyykykyyyykykyydo.....
.....oyyyykyyyyykyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyrryyyyyyyyyyrrdo.....
.....oyyyyyyymmyyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.....oyyyyyyyooyyyyyydo.....
.......oyyyyyyyyyyydo.......
.........oyyyyyyyyo.........
........oyyyyyyyyyyo........
........oyyccccccyyo........
....owwooyyccccccyyoowwo....
...owwwooyyccccccyyoowwwo...
...owwwooyyccccccyyoowwwo...
....owwooyyccccccyyoowwo....
.....oo.oyyccccccyyo.oo.....
........oyyddddddyyo..oyo...
.........oyyyyyyyyo....oyo..
........oddooooooddo...oppo.
.........oo......oo.........
............................
'@

$nlAlertB = Rows @'
............................
......owo...owwo...owo......
......owwo.owwwwo.owwwo.....
.......owo..wwww..owo.......
........oyyywwwwyyyo........
.......ollllllllllllo.......
......oyyyyyyyyyyyyyyo......
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyykkkyyyykkkyydo.....
.....oyyykykyyyykykyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyyyyyyyyyyyyyyydo.....
.....oyrryyyyyyyyyyrrdo.....
.....oyyyyyyymmyyyyyydo.....
.....oyyyyyyoppoyyyyydo.....
.....oyyyyyyyppyyyyyydo.....
.......oyyyyyyyyyyydo.......
.........oyyyyyyyyo.........
........oyyyyyyyyyyo........
........oyyccccccyyo........
....owwooyyccccccyyoowwo....
...owwwooyyccccccyyoowwwo...
...owwwooyyccccccyyoowwwo...
....owwooyyccccccyyoowwo....
.....oo.oyyccccccyyo.oo.....
........oyyddddddyyo..oyo...
.........oyyyyyyyyo....oyo..
........oddooooooddo...oppo.
.........oo......oo.........
............................
'@

# ============================================================
# 小雪（像素小雪狐：大耳 + 冰蓝围巾 + 左侧蓬蓬尾）
# ============================================================
$snIdleA = Rows @'
............................
.......oo..........oo.......
......owwo........owwo......
.....owwwo........owwwo.....
.....owpwo........owpwo.....
.....owppwo......owppwo.....
....owppwo.......owppwo.....
......oiiiiiiiiiiiiiio......
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwkkkkwwkkkkwwbo.....
.....owwwwkkwwwwkkwwwbo.....
.....owppwwwwwwwwwppwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwnnwwwwwwbo.....
.....owwwwwwowwowwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
......owwwwwwwwwwwwwbo......
........owwwwwwwwwwo........
..........owwwwwwo..........
........oeeeeeeeeeeo........
........oeeeeeeeeeeo........
........ofeeeeeeeefo........
.........owwwwwwffo.........
..owwo...owwwwwwffo.........
.owwwwo..owwwwwfffo.........
owwwwwwo.owwwwwwffo.........
owwwwwwo.owwwwwwbbo.........
.owwwwo...obo..obo..........
..owwo.....oo...oo..........
............................
'@

$snIdleB = Rows @'
............................
............................
.......oo..........oo.......
......owwo........owwo......
.....owwwo........owwwo.....
.....owpwo........owpwo.....
.....owppwo......owppwo.....
....owppwo.......owppwo.....
......oiiiiiiiiiiiiiio......
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwkkkkwwkkkkwwbo.....
.....owwwwkkwwwwkkwwwbo.....
.....owppwwwwwwwwwppwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwnnwwwwwwbo.....
.....owwwwwwowwowwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
......owwwwwwwwwwwwwbo......
........owwwwwwwwwwo........
..........owwwwwwo..........
........oeeeeeeeeeeo........
........ofeeeeeeeefo........
........ofeeeeeeeefo........
...owwo..owwwwwwffo.........
..owwwwo.owwwwwfffo.........
.owwwwwwoowwwwwwffo.........
.owwwwwwoowwwwwwbbo.........
..owwwwo..obo..obo..........
...owwo....oo...oo..........
............................
'@

$snThinkA = Rows @'
............................
.......oo..........oo.......
......owwo........owwo......
.....owwwo........owwwo.....
.....owpwo........owpwo.....
.....owppwo......owppwo.....
....owppwo.......owppwo.....
......oiiiiiiiiiiiiiio......
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwkkkkwwkkkkwwbo.....
.....owwwkkkkwwkkkkwwbo.....
.....owppwwwwwwwwwppwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwnnwwwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
......owwwwwwwwwwwwwbo......
........owwwwwwwwwwo........
..........owwwwwwo..........
........oeeeeeeeeeeo........
........oeeeeeeeeeeo........
........ofeeeeeeeefo........
.........owwwwwwffo.........
..owwo...owwwwwwffo.........
.owwwwo..owwwwwfffo.........
owwwwwwo.owwwwwwffo.........
owwwwwwo.owwwwwwbbo.........
.owwwwo...obo..obo..........
..owwo.....oo...oo..........
............................
'@

$snThinkB = Rows @'
............................
.......oo..........oo.......
......owwo........owwo......
.....owwwo........owwwo.....
.....owpwo........owpwo.....
.....owppwo......owppwo.....
....owppwo.......owppwo.....
......oiiiiiiiiiiiiiio......
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwkkkkwwkkkkwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owppwwwwwwwwwppwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwnnwwwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
......owwwwwwwwwwwwwbo......
........owwwwwwwwwwo........
..........owwwwwwo..........
........oeeeeeeeeeeo........
........oeeeeeeeeeeo........
........ofeeeeeeeefo........
.........owwwwwwffo.........
..owwo...owwwwwwffo.........
.owwwwo..owwwwwfffo.........
owwwwwwo.owwwwwwffo.........
owwwwwwo.owwwwwwbbo.........
.owwwwo...obo..obo..........
..owwo.....oo...oo..........
............................
'@

$snSpeakA = Rows @'
............................
.......oo..........oo.......
......owwo........owwo......
.....owwwo........owwwo.....
.....owpwo........owpwo.....
.....owppwo......owppwo.....
....owppwo.......owppwo.....
......oiiiiiiiiiiiiiio......
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwkwwkwwkwwkwwbo.....
.....owwwwkkwwwwkkwwwbo.....
.....owppwwwwwwwwwppwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwnnwwwwwwbo.....
.....owwwwwwoppowwwwwbo.....
.....owwwwwwwppwwwwwwbo.....
......owwwwwwwwwwwwwbo......
........owwwwwwwwwwo........
..........owwwwwwo..........
........oeeeeeeeeeeo........
........oeeeeeeeeeeo........
........ofeeeeeeeefo........
.........owwwwwwffo.........
..owwo...owwwwwwffo.........
.owwwwo..owwwwwfffo.........
owwwwwwo.owwwwwwffo.........
owwwwwwo.owwwwwwbbo.........
.owwwwo...obo..obo..........
..owwo.....oo...oo..........
............................
'@

$snAlertA = Rows @'
............................
.......oo..........oo.......
......owwo........owwo......
.....owwwo........owwwo.....
.....owpwo........owpwo.....
.....owppwo......owppwo.....
....owppwo.......owppwo.....
......oiiiiiiiiiiiiiio......
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwkkkkwwkkkkwwbo.....
.....owwwkwwkwwkwwkwwbo.....
.....owppwwwwwwwwwppwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwnnwwwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
.....owwwwwwwoowwwwwwbo.....
......owwwwwwwwwwwwwbo......
........owwwwwwwwwwo........
..........owwwwwwo..........
........oeeeeeeeeeeo........
........oeeeeeeeeeeo........
........ofeeeeeeeefo........
.........owwwwwwffo.........
..owwo...owwwwwwffo.........
.owwwwo..owwwwwfffo.........
owwwwwwo.owwwwwwffo.........
owwwwwwo.owwwwwwbbo.........
.owwwwo...obo..obo..........
..owwo.....oo...oo..........
............................
'@

$snAlertB = Rows @'
............................
.......oo..........oo.......
......owwo........owwo......
.....owwwo........owwwo.....
.....owpwo........owpwo.....
.....owppwo......owppwo.....
....owppwo.......owppwo.....
......oiiiiiiiiiiiiiio......
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwkwwkwwkwwkwwbo.....
.....owwwwkkwwwwkkwwwbo.....
.....owppwwwwwwwwwppwbo.....
.....owwwwwwwwwwwwwwwbo.....
.....owwwwwwwnnwwwwwwbo.....
.....owwwwwwoppowwwwwbo.....
.....owwwwwwwppwwwwwwbo.....
......owwwwwwwwwwwwwbo......
........owwwwwwwwwwo........
..........owwwwwwo..........
........oeeeeeeeeeeo........
........oeeeeeeeeeeo........
........ofeeeeeeeefo........
.........owwwwwwffo.........
..owwo...owwwwwwffo.........
.owwwwo..owwwwwfffo.........
owwwwwwo.owwwwwwffo.........
owwwwwwo.owwwwwwbbo.........
.owwwwo...obo..obo..........
..owwo.....oo...oo..........
............................
'@

# ---- 生成 8 个 SVG ----
$nl = Join-Path $root 'lingxi-nailong'
$sn = Join-Path $root 'lingxi-snow'

New-SkinSvg (Join-Path $nl 'idle.svg') $palNailong $nlIdleA $nlIdleB 1.1 @(
  @{ rows = $blinkNailong; x = 9; y = 10; cls = 'blink' }
) $false

New-SkinSvg (Join-Path $nl 'thinking.svg') $palNailong $nlThinkA $nlThinkB 1.7 @(
  @{ rows = $blinkNailong; x = 9; y = 10; cls = 'blink' },
  @{ rows = $tdotNailong; x = 20; y = 4; cls = 'td' },
  @{ rows = $tdotNailong; x = 23; y = 2; cls = 'td td2' },
  @{ rows = $tdotNailong; x = 26; y = 0; cls = 'td td3' }
) $false

New-SkinSvg (Join-Path $nl 'speaking.svg') $palNailong $nlSpeakA $nlIdleA 0.44 @(
  @{ rows = $noteNailong; x = 22; y = 1; cls = 'note' }
) $false

New-SkinSvg (Join-Path $nl 'alert.svg') $palNailong $nlAlertA $nlAlertB 0.46 @(
  @{ rows = $markAll; x = 25; y = 0; cls = 'mark' }
) $true

New-SkinSvg (Join-Path $sn 'idle.svg') $palSnow $snIdleA $snIdleB 1.1 @(
  @{ rows = $blinkSnow; x = 9; y = 10; cls = 'blink' }
) $false

New-SkinSvg (Join-Path $sn 'thinking.svg') $palSnow $snThinkA $snThinkB 1.7 @(
  @{ rows = $blinkSnow; x = 9; y = 10; cls = 'blink' },
  @{ rows = $tdotSnow; x = 20; y = 4; cls = 'td' },
  @{ rows = $tdotSnow; x = 23; y = 2; cls = 'td td2' },
  @{ rows = $tdotSnow; x = 26; y = 0; cls = 'td td3' }
) $false

New-SkinSvg (Join-Path $sn 'speaking.svg') $palSnow $snSpeakA $snIdleA 0.44 @(
  @{ rows = $noteSnow; x = 22; y = 1; cls = 'note' }
) $false

New-SkinSvg (Join-Path $sn 'alert.svg') $palSnow $snAlertA $snAlertB 0.46 @(
  @{ rows = $markAll; x = 25; y = 0; cls = 'mark' }
) $true

Write-Host '全部像素皮肤生成完毕。'
